<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="F_denormalization" Id="{86002d00-668b-43f5-be54-085674f22bae}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_denormalization : LREAL
VAR_INPUT
	x : LREAL;
	mean : LREAL;
	std : LREAL;
END_VAR
VAR_OUTPUT
	x_denor : LREAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[x_denor := x * std + mean;]]></ST>
    </Implementation>
    <LineIds Name="F_denormalization">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>