<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="F_silu" Id="{776c6fa3-c0e3-465d-991a-a3924569a053}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_silu : lreal
VAR_INPUT
	x : LREAL;
END_VAR

]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_silu := x / (1 + exp(-x));]]></ST>
    </Implementation>
    <LineIds Name="F_silu">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>