<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="F_sigmoid" Id="{06514012-fa58-4a56-a5df-a893c7a5bf78}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_sigmoid : LREAL
VAR_INPUT
	x : LREAL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_sigmoid := 1 / (1 + exp(-x));]]></ST>
    </Implementation>
    <LineIds Name="F_sigmoid">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>