<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="F_softplus" Id="{595aca46-1dce-4de1-8177-d23da8043630}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_softplus : lreal
VAR_INPUT
	x : LREAL;
END_VAR

]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_softplus := log(exp(x)+1);]]></ST>
    </Implementation>
    <LineIds Name="F_softplus">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>