<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="F_exponential" Id="{d871f8f7-3aa5-4062-900b-46dd2ce56fdc}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_exponential : lreal
VAR_INPUT
	x : LREAL;
END_VAR

]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_exponential := exp(x);]]></ST>
    </Implementation>
    <LineIds Name="F_exponential">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>