<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="F_softsign" Id="{8b3be192-4fc8-4ea0-b942-0ae23a6c8559}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION F_softsign : lreal
VAR_INPUT
	x : LREAL;
END_VAR

]]></Declaration>
    <Implementation>
      <ST><![CDATA[F_softsign := x / (abs(x) + 1);]]></ST>
    </Implementation>
    <LineIds Name="F_softsign">
      <LineId Id="7" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>